/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsignaturasRouteImport } from './routes/asignaturas'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as HorarioRouteImport } from './routes/horario'
import { Route as ProgresoRouteImport } from './routes/progreso'
import { Route as SemanaRouteImport } from './routes/semana'
import { Route as TarjetasRouteImport } from './routes/tarjetas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsignaturasRoute = AsignaturasRouteImport.update({
  id: '/asignaturas',
  path: '/asignaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const HorarioRoute = HorarioRouteImport.update({
  id: '/horario',
  path: '/horario',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const SemanaRoute = SemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => rootRouteImport,
} as any)
const TarjetasRoute = TarjetasRouteImport.update({
  id: '/tarjetas',
  path: '/tarjetas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asignaturas': typeof AsignaturasRoute
  '/calendario': typeof CalendarioRoute
  '/horario': typeof HorarioRoute
  '/progreso': typeof ProgresoRoute
  '/semana': typeof SemanaRoute
  '/tarjetas': typeof TarjetasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asignaturas': typeof AsignaturasRoute
  '/calendario': typeof CalendarioRoute
  '/horario': typeof HorarioRoute
  '/progreso': typeof ProgresoRoute
  '/semana': typeof SemanaRoute
  '/tarjetas': typeof TarjetasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asignaturas': typeof AsignaturasRoute
  '/calendario': typeof CalendarioRoute
  '/horario': typeof HorarioRoute
  '/progreso': typeof ProgresoRoute
  '/semana': typeof SemanaRoute
  '/tarjetas': typeof TarjetasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asignaturas'
    | '/calendario'
    | '/horario'
    | '/progreso'
    | '/semana'
    | '/tarjetas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asignaturas'
    | '/calendario'
    | '/horario'
    | '/progreso'
    | '/semana'
    | '/tarjetas'
  id:
    | '__root__'
    | '/'
    | '/asignaturas'
    | '/calendario'
    | '/horario'
    | '/progreso'
    | '/semana'
    | '/tarjetas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsignaturasRoute: typeof AsignaturasRoute
  CalendarioRoute: typeof CalendarioRoute
  HorarioRoute: typeof HorarioRoute
  ProgresoRoute: typeof ProgresoRoute
  SemanaRoute: typeof SemanaRoute
  TarjetasRoute: typeof TarjetasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asignaturas': {
      id: '/asignaturas'
      path: '/asignaturas'
      fullPath: '/asignaturas'
      preLoaderRoute: typeof AsignaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horario': {
      id: '/horario'
      path: '/horario'
      fullPath: '/horario'
      preLoaderRoute: typeof HorarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semana': {
      id: '/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof SemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarjetas': {
      id: '/tarjetas'
      path: '/tarjetas'
      fullPath: '/tarjetas'
      preLoaderRoute: typeof TarjetasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsignaturasRoute: AsignaturasRoute,
  CalendarioRoute: CalendarioRoute,
  HorarioRoute: HorarioRoute,
  ProgresoRoute: ProgresoRoute,
  SemanaRoute: SemanaRoute,
  TarjetasRoute: TarjetasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
